
#include<bits/stdc++.h>

using namespace std;
int main(){
int a=10;
int b=0;

try{
if(b == 0)throw 'a';

cout<<a/b<<endl;
}
catch(int e){
cout<<e<<" throw from the try block.!"<<endl;
}catch(char err){
cout<<err<<" throw from the try block.!"<<endl;
}

cout<<"program ended normally"<<endl;

return 0;
}
